spring.application.name=permissions-service
spring.mvc.problemdetails.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never
